print("Welcome to RiddleMaster!")
print("Get ready to solve some intriguing riddles and test your wits!")
print("what is your name?")
name = input("Enter your name: ")
print(f"Hello, {name}! Let's begin your riddle adventure!")